// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDbxhP-G7gW2zapbuNFJUxrcMkBxR8VvQ',
    appId: '1:40657209345:web:3fa2961ca7a92a1b261800',
    messagingSenderId: '40657209345',
    projectId: 'chat-material-3',
    authDomain: 'chat-material-3.firebaseapp.com',
    storageBucket: 'chat-material-3.appspot.com',
    measurementId: 'G-31SX2NK5LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwidAF5-pR1i9kNnGu1ysh7AhPnamF7L4',
    appId: '1:40657209345:android:1260ad64ee090713261800',
    messagingSenderId: '40657209345',
    projectId: 'chat-material-3',
    storageBucket: 'chat-material-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0O7OOluZ5LU7wOoVt1ztHd1ed_2-7bpc',
    appId: '1:40657209345:ios:eff22d92d038642b261800',
    messagingSenderId: '40657209345',
    projectId: 'chat-material-3',
    storageBucket: 'chat-material-3.appspot.com',
    iosBundleId: 'com.example.chatMaterial3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0O7OOluZ5LU7wOoVt1ztHd1ed_2-7bpc',
    appId: '1:40657209345:ios:eff22d92d038642b261800',
    messagingSenderId: '40657209345',
    projectId: 'chat-material-3',
    storageBucket: 'chat-material-3.appspot.com',
    iosBundleId: 'com.example.chatMaterial3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDbxhP-G7gW2zapbuNFJUxrcMkBxR8VvQ',
    appId: '1:40657209345:web:211dbe41e5f0e9d4261800',
    messagingSenderId: '40657209345',
    projectId: 'chat-material-3',
    authDomain: 'chat-material-3.firebaseapp.com',
    storageBucket: 'chat-material-3.appspot.com',
    measurementId: 'G-N24QSX3BYX',
  );
}
